#!/usr/bin/perl -w

use strict;
use warnings;

use Data::Dumper;
use JSON;
use LWP::Simple;

my @node_ids = ( 'c6:4a:00:fc:22:05', '12:fe:ed:2b:15:ae' );
my %node_id;

sub get_node_data {
    my $content = get('http://map.md.freifunk.net/nodes.json');
    die 'Could not get it!' unless defined $content;

    my $nodes_ref = decode_json($content);

    foreach my $node ( @{ $nodes_ref->{'nodes'} } ) {
        foreach my $id ( @node_ids ) {
            if ( $node->{'id'} eq $id ) {
                $node_id{ $id } = $node->{'clientcount'};
            }
        }
    }
}

if ($ARGV[0] and $ARGV[0] eq "config") {
    print "graph_title Alex' Freifunk Knoten\n";
    print "graph_args --base 1000 --lower-limit 0\n";
    print "graph_scale no\n";
    print "graph_category freifunk\n";
    print "balkonx.label balkonx\n";
    print "balkonx.type GAUGE\n";
    print "balkonx.min 0\n";
    print "balkony.label balkony\n";
    print "balkony.type GAUGE\n";
    print "balkony.min 0\n";
    exit 0;
}

foreach my $node ( @node_ids ) {
    $node_id{ $node } = 0;
}

get_node_data();

$node_id{'c6:4a:00:fc:22:05'}--;

print "balkony.value $node_id{'c6:4a:00:fc:22:05'}\n";
print "balkonx.value $node_id{'12:fe:ed:2b:15:ae'}\n";

# vim:ft=perl
